### ISSUE TITLE
setMode supported from API device. Ring account has alarm present so use alarm modes!

### ISSUE THREAD

**Issue by rumym** [HubitatCommunity/hubitat_ring_integration#40]
Hubitat recently stopped arming/disarming however, everything else seems to work fine. I started getting this error: setMode supported from API device. Ring account has alarm present so use alarm modes!

Any suggestions on what happened?

**Comment by cmorse** [comment]
This error normally means that you need to use the alarm hub to change alarm modes, not the api device
