### ISSUE TITLE
Adding instance failed

### ISSUE THREAD

**Issue by prubin3390** [HubitatCommunity/hubitat_ring_integration#50]
I tried adding an instance, it failed because of missing drivers.  I went into the package  manager did a modify and added the drivers.  I could not find the partial app creating so I had to start over.  When I select the location I get:

Error: A device with the same device network ID exists, Please use a different DNI

There are also two copies of the app showing under add user app.

**Comment by cmorse** [comment]
Not sure how multiple instances of the app could be installed. Hubitat is supposed to be preventing that.
